Improved use of tool

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,9 +1,5 @@
 #!/usr/bin/env bash
 
-# Fail / Interruption handling
-set -e
-trap 'echo "Interrupted. Exiting safely."; exit 130' INT
-
 # ----- colors -----
 ERROR=$'\033[31m'
 SUCCESS=$'\033[32m'
@@ -26,6 +22,10 @@ dsh_print() {
 
 
 
+# Fail / Interruption handling
+set -e
+trap 'echo "Interrupted. Exiting safely."; exit 130' INT
+
 dsh_print "Checking if required dependencies are installed" "$INFO"
 missing_deps=()
 
@@ -38,6 +38,10 @@ if (( ${#missing_deps[@]} > 0 )); then
     dsh_print "EXIT 1" "$ERROR"
     exit 1
 fi
+# Ask for sudo now if docker isn't started opposed to during the scrip
+# Needed to temporarily launch to install plugin(s)
+systemctl is-active --quiet docker || { dsh_print "Asking for sudo to start docker.service" "$INFO"; \
+sudo systemctl start docker; }
 
 
 
@@ -49,10 +53,12 @@ if [[ ! -d "./deepseek-harness" ]]; then
 fi
 
 dsh_print "Building Docker image (may take a while)" "$INFO"
-docker compose build -q
+docker compose build -q 2>/dev/null
 
 dsh_print "Creating Docker container" "$INFO"
-docker compose create
+docker compose create --quiet-pull 2>/dev/null
+
+
 
 DSH_DIR="$(pwd)"
 BIN_DIR="$HOME/bin"
@@ -72,24 +78,26 @@ DSH_DIR="$DSH_DIR"
 
 case "\$1" in
   start)
-    sudo systemctl start docker
-    docker compose -p dsh -f "\$DSH_DIR/compose.yml" up -d
-    echo "dsh web: http://127.0.0.1:3080"
+    echo "[DHS] Starting..."
+    systemctl is-active --quiet docker || sudo systemctl start docker
+    docker compose -p dsh -f "\$DSH_DIR/compose.yml" up -d --quiet-pull 2>/dev/null
+    echo "[DHS] http://127.0.0.1:3080"
     ;;
   stop)
-    docker compose -p dsh -f "\$DSH_DIR/compose.yml" stop
+    echo "[DHS] Stopping..."
+    docker compose -p dsh -f "\$DSH_DIR/compose.yml" stop 2>/dev/null
     ;;
   restart)
-    docker compose -p dsh -f "\$DSH_DIR/compose.yml" stop
-    docker compose -p dsh -f "\$DSH_DIR/compose.yml" up -d
-    echo "dsh web: http://127.0.0.1:3080"
+    docker compose -p dsh -f "\$DSH_DIR/compose.yml" stop 2>/dev/null
+    docker compose -p dsh -f "\$DSH_DIR/compose.yml" up -d --quiet-pull 2>/dev/null
+    echo "[DHS] http://127.0.0.1:3080"
     ;;
 
   update)
     cd "\$DSH_DIR" && git pull
     ;;
   uninstall)
-    docker compose -p dsh -f "\$DSH_DIR/compose.yml" down -v --rmi local
+    docker compose -p dsh -f "\$DSH_DIR/compose.yml" down -v --rmi local 2>/dev/null
     echo "Removed Docker files"
     rm -rf "\$HOME/bin/dsh"
     echo "Removed dsh home binary"
@@ -119,12 +127,16 @@ EOF
 chmod a+x "$WRAPPER"
 dsh_print "Created dsh wrapper binary at:$LOCATION $WRAPPER$ENDCOLOR" "$SUCCESS"
 
-dsh_print "Installing recommended plugins" "$INFO"
+
+
+dsh_print "Installing recommended plugin(s)" "$INFO"
 dsh start
-dsh app plugin --profile web add dsh-plugin # invokes the just created dsh binary
+dsh plugin --profile web add dsh-plugin
 dsh stop
 dsh_print "Installed: dsh-plugin" "$SUCCESS"
 
+
+# Create ~/.dsh if not present already
 DSH_DIR="$HOME/.dsh"
 if [ ! -d "$DSH_DIR" ]; then
   mkdir -p "$DSH_DIR"
@@ -132,6 +144,8 @@ elif [ "$(stat -c '%u' "$DSH_DIR")" != "$(id -u)" ]; then
   chown -R "$(id -u):$(id -g)" "$DSH_DIR"
   dsh_print "Changed $LOCATION~/.dsh$ENDCOLOR ownership from root (assigned by DSH build) to your user '$(WHOAMI)'" "$SUCCESS"
 fi
+
+
 dsh_print "" "$SUCCESS"
 dsh_print "IMPORTANT: Currently DSH is unable to be hosted on 0.0.0.0, since: 'it would expose remote code execution to the network'." "$IMPORTANT"
 dsh_print "This would only be a concern if ran on a local-machine," "$IMPORTANT"
@@ -142,6 +156,9 @@ dsh_print "" "$IMPORTANT"
 dsh_print "To avoid sandboxing issues, make sure to always run with 'Full Access'" "$IMPORTANT"
 dsh_print "Doing this is NOT a security concern as Docker provides isolation through volume mounting" "$IMPORTANT"
 dsh_print "" "$IMPORTANT"
+
+
+
 dsh_print "SUCCESSFULLY INSTALLED" "$SUCCESS"
 dsh_print "$COMMAND  dsh start$ENDCOLOR" "$INFO"
 dsh_print "$COMMAND  dsh stop$ENDCOLOR" "$INFO"
